# Generated by Django 3.2.19 on 2023-06-22 21:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20230622_1759'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cart',
            name='\nrecipes_cart recipe is cart alredy\n',
        ),
        migrations.RemoveConstraint(
            model_name='favoritesrecipes',
            name='\nrecipes_favoritesrecipes recipe is favorite alredy\n',
        ),
        migrations.RemoveConstraint(
            model_name='ingredients',
            name='\nrecipes_ingredients ingredient alredy added\n',
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='amount',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, 'Количество ингредиента должно быть больше 0.')], verbose_name='Количество'),
        ),
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.UniqueConstraint(fields=('recipe', 'user'), name='\nrecipes_cart recipe is cart already\n'),
        ),
        migrations.AddConstraint(
            model_name='favoritesrecipes',
            constraint=models.UniqueConstraint(fields=('recipe', 'user'), name='\nrecipes_favoritesrecipes recipe is favorite already\n'),
        ),
        migrations.AddConstraint(
            model_name='ingredients',
            constraint=models.UniqueConstraint(fields=('recipe', 'ingredients'), name='\nrecipes_ingredients ingredient already added\n'),
        ),
    ]
