# Generated by Django 3.2.19 on 2023-06-22 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userfoodgram',
            name='users_userfoodgram_name_unique',
        ),
    ]
